### ISSUE TITLE
Add Hive's icon 

### ISSUE THREAD

**Issue by jiminhsieh** [plantuml-stdlib/cicon-plantuml-sprites#6]
Is it possible to add Hive icon to sprites list? Thanks.

**Comment by rabelenda** [comment]
Hello, this project is just a conversion of [cloud insight icons](https://github.com/cloudinsight/cicon) to PlantUML format. If you ask them to add the icon, this project can easily convert it to PlantUML and publish it for easy consumption in the tool.

Regards.
